server:
    port: 8083

spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
            - id: produto
              uri: lb://produto
              predicates:
                - Path=/api/produto/**
            - id: pedido
              uri: lb://pedido
              predicates:
                - Path=/api/pedido/**
            - id: user
              uri: lb://user
              predicates:
                - Path=/api/usuario/**
            # httpclient:
            #     connect-timeout: 10000

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka




